// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADbBnE4pMABrCriDo3SJgE38Kcom-QQK0',
    appId: '1:811189271096:web:382e82eaba0074cdff44cd',
    messagingSenderId: '811189271096',
    projectId: 'votacao-rainha-do-rodeio',
    authDomain: 'votacao-rainha-do-rodeio.firebaseapp.com',
    storageBucket: 'votacao-rainha-do-rodeio.firebasestorage.app',
    measurementId: 'G-B7D3X85F26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOc3ppe3g5K3DMW4x_hXUbFirg2JvN4f4',
    appId: '1:811189271096:android:ae09227ec5acec4dff44cd',
    messagingSenderId: '811189271096',
    projectId: 'votacao-rainha-do-rodeio',
    storageBucket: 'votacao-rainha-do-rodeio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTNY19m9ISXHsltnuNVtUy5BnwYMLw338',
    appId: '1:811189271096:ios:e5ff879bfcea01b7ff44cd',
    messagingSenderId: '811189271096',
    projectId: 'votacao-rainha-do-rodeio',
    storageBucket: 'votacao-rainha-do-rodeio.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTNY19m9ISXHsltnuNVtUy5BnwYMLw338',
    appId: '1:811189271096:ios:e5ff879bfcea01b7ff44cd',
    messagingSenderId: '811189271096',
    projectId: 'votacao-rainha-do-rodeio',
    storageBucket: 'votacao-rainha-do-rodeio.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADbBnE4pMABrCriDo3SJgE38Kcom-QQK0',
    appId: '1:811189271096:web:296272ef4013f22aff44cd',
    messagingSenderId: '811189271096',
    projectId: 'votacao-rainha-do-rodeio',
    authDomain: 'votacao-rainha-do-rodeio.firebaseapp.com',
    storageBucket: 'votacao-rainha-do-rodeio.firebasestorage.app',
    measurementId: 'G-334PL3VSE3',
  );
}
